Added Build Script and Dependabot, Updated spring boot version to 3.2.2
quantics-io/multitenant-oauth2-spring-boot-starter pull request #14
Opened 2024-02-07 07:21 UTC by garvit-joshi

2024-02-07 07:24 UTC, garvit-joshi commented
Also, Can we have the versions of this as same as spring boot starter.
Such as multitenant-oauth2-spring-boot-starter version 3.2.2 should have spring boot version 3.2.2.

2024-02-07 08:09 UTC, garvit-joshi commented
Build Script Logs: https://github.com/garvit-joshi/multitenant-oauth2-spring-boot-starter/actions/runs/7811077921

2024-02-10 19:27 UTC, garvit-joshi commented
@jomatt Any Update?

2024-02-11 11:53 UTC, jomatt requested changes

2024-02-11 11:53 UTC, jomatt commented on .github/workflows/build.yml
> +            path: /home/runner/work/multitenant-oauth2-spring-boot-starter/multitenant-oauth2-spring-boot-starter/target/*.jar
Instead of hard-coding the path, I guess you can use the `GITHUB_WORKSPACE` env variable

2024-02-11 12:03 UTC, jomatt commented
@garvit-joshi thx a lot for opening this PR and contributing to the library!

I had the same idea regarding synchronizing the version in the beginning, but then decided against it because I had to publish various releases for the same Spring Boot version. I think in general it's a good idea to use the same version as  Spring Boot. However, how would you handle hotfix versions, e.g. if we need to provide a fix for version 3.2.2 - how do you suggest to version it? 

Also, it would be really helpful to automate the publishing of the build artifacts to Maven central. This is already on my todo list, but so far I did not find the time to add it. Would you be available to add this to the GH workflows?

2024-02-17 05:12 UTC, garvit-joshi commented
Hi,
I found one workaround for the versioning:
Oracle has versioning different from Semver where the versioning is the form of w.x.y.z. We can make the versions 3.2.2.x where x is the patch version. 
Oracle Maven Packages: [here](https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc10).

I will try to add a new workflow for the maven publishing when I get time.

2024-03-10 12:23 UTC, garvit-joshi commented
Hi @jomatt ,

Apologies for the delay. I have made few chages, however i am not that confident on releasing to maven workflow, as I could not test it.

Could you please check if i am missing something here

2025-03-08 09:49 UTC, closed without merging